### ISSUE TITLE
Failure console

### ISSUE THREAD

**Issue by Robka87** [elsucco/altv-sit#1]
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/altv/server/resources/sit_01/server/index.js' imported from /home/altv/server/
    at finalizeResolution (internal/modules/esm/resolve.js:265:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at defaultResolve (internal/modules/esm/resolve.js:810:11)
    at resolve (embedder_main_5.js:22:16)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at Loader.import (internal/modules/esm/loader.js:165:28)
    at embedder_main_5.js:30:35
    at embedder_main_5.js:43:3 {
  code: 'ERR_MODULE_NOT_FOUND'
```

What the Modul for this plugin?

**Comment by Robka87** [comment]
Newed Failure:

[17:13:07] Loading resource sit_02
(node:8700) Warning: To load an ES module, set "type": "module" in the package.j                            son or use the .mjs extension.
(node:8700) Warning: To load an ES module, set "type": "module" in the package.j                            son or use the .mjs extension.
/home/altv/server/resources/sit_02/server/index.js:1
import * as alt from 'alt-server';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async embedder_main_5.js:30:16
[17:13:07][Error] Failed to load resource sit_02

**Comment by jonesXYZ** [comment]
Wie dumm kann jemand sein?
Du: JA.

**Comment by mcschirl** [comment]
This is not a failure coming from the code. You need to add the following line to your package.json in your main server directory. 

"type": "module"

the line to be added.
