### ISSUE TITLE
Can't load resource

### ISSUE THREAD

**Issue by editsons** [elsucco/altv-sit#2]
I downloaded the release and extracted all the content into a folder in the resource folder. Then I added the folder name in the server.cfg resource list. Now when I start the server it can't load the resource. (Adding a package.json file with content equals "{"type": "module" }" fixes the problem.) Server output:

[17:07:36] Loading resource sit
(node:6704) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(node:6704) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
D:\AltV\server\resources\sit\server\index.js:1
import * as alt from 'alt-server';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async embedder_main_2.js:30:16
[17:07:36][Error] Failed to load resource sit

**Comment by V4M0N0S** [comment]
Adding a package.json file with content equals "{"type": "module" }" fixes the problem.

This should be a standart thing if you run an alt:V server with JS modules. Its not an issue, its your fault.
